### ISSUE TITLE
Write usage documentation

### ISSUE THREAD

**Issue by jthomerson** [silvermine/lambda-express#16]
Need to write usage documentation in the README. It should include:

 * any differences from the API of Express (notably, mounting sub-routers)
 * examples of middleware, request handlers, error handlers
 * hello world

**Comment by jthomerson** [comment]
Explanation of the event paths you need, e.g.:

```
functions:
   api:
      name: 'your-fn-name'
      handler: src/YourAPI.handler
      memorySize: 512
      timeout: 2
      events:
         - http: 'ANY /'
         - http: 'ANY /{proxy+}'
```
